ExpeditionHelper_SOL/Controllers/VersionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExpeditionHelper_SOL.Models;
using PagedList;

namespace ExpeditionHelper_SOL.Controllers
{
    public class VersionController : BaseController
    {
        // Initialisation Base de données
        private ExpeditionHelper_SOLEntities db = new ExpeditionHelper_SOLEntities();

        // Index Version
        public ActionResult Index(string currentFilter, string searchString, int? page)
        {
            var VersionLinq = from version in db.TB_VERSION
                      select version;

            //Gestion du numéro de page
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            //Gestion de la recherche par nom
            if (!String.IsNullOrEmpty(searchString))
            {
                VersionLinq = VersionLinq.Where(version => version.Nom.Contains(searchString));
            }

            VersionLinq = VersionLinq.OrderBy(version => version.Nom);

            //Gestion des pages
            int pageSize = 25;
            int pageNumber = (page ?? 1);

            return View(VersionLinq.ToPagedList(pageNumber, pageSize));
        }

        // Liste Ajout Version
        public ActionResult Create()
        {
            return View();
        }

        // Ajout Version
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nom,Auteur,Description,Date_Prod,prod")] TB_VERSION tB_VERSION)
        {
            if (ModelState.IsValid)
            {
                if (tB_VERSION.prod == "1")
                {
                    foreach (var item in db.TB_VERSION.ToList())
                    {
                        item.prod = "0";

                        db.Entry(item).State = EntityState.Modified;
                        db.SaveChanges();
                    }
                }
                db.TB_VERSION.Add(tB_VERSION);

                // Création des logs
                TB_LOG tB_LOG = new TB_LOG();
                tB_LOG.Login = Session["login"].ToString();
                tB_LOG.Date = DateTime.Now.ToString();
                tB_LOG.Action = "Création d'une nouvelle version : '" + tB_VERSION.Nom + "'";
                tB_LOG.Texte = "Nom de la version : '" + tB_VERSION.Nom + "'/Separation/Description : '" + tB_VERSION.Description + "'";
                db.TB_LOG.Add(tB_LOG);

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tB_VERSION);
        }

        // Liste Edition Version
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_VERSION tB_VERSION = db.TB_VERSION.Find(id);

            var VersionLinq = from version in db.TB_VERSION
                          where version.Id == id
                          select version;

            ViewBag.VersionLinq = VersionLinq;

            if (tB_VERSION == null)
            {
                return HttpNotFound();
            }
            return View(tB_VERSION);
        }

        // Edition Version
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nom,Auteur,Description,Date_Prod,prod")] TB_VERSION tB_VERSION)
        {

            if (ModelState.IsValid)
            {
                db.Entry(tB_VERSION).State = EntityState.Modified;
                db.SaveChanges();
            }


            if (tB_VERSION.prod == "1")
            {
                var VersionLinq = from version in db.TB_VERSION
                                  where version.Id != tB_VERSION.Id
                                  select version;

                foreach (var item in VersionLinq)
                {
                    item.prod = "0";
                    if (ModelState.IsValid)
                    {
                        db.Entry(item).State = EntityState.Modified;
                    }
                }
            }

            // Création des logs
            TB_LOG tB_LOG = new TB_LOG();
            tB_LOG.Login = Session["login"].ToString();
            tB_LOG.Date = DateTime.Now.ToString();
            tB_LOG.Action = "Modification d'une version : '" + tB_VERSION.Nom + "'";
            tB_LOG.Texte = "Nouveau nom de la version : '" + tB_VERSION.Nom + "'/Separation/Nouvelle description : '" + tB_VERSION.Description + "'";
            db.TB_LOG.Add(tB_LOG);

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // Liste Suppression Version
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_VERSION tB_VERSION = db.TB_VERSION.Find(id);

            var VersionLinq = from version in db.TB_VERSION
                              where version.Id == id
                              select version;

            ViewBag.VersionLinq = VersionLinq;
            if (tB_VERSION == null)
            {
                return HttpNotFound();
            }
            return View(tB_VERSION);
        }

        // Liste Suppression Version
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TB_VERSION tB_VERSION = db.TB_VERSION.Find(id);
            db.TB_VERSION.Remove(tB_VERSION);

            // Création des logs
            TB_LOG tB_LOG = new TB_LOG();
            tB_LOG.Login = Session["login"].ToString();
            tB_LOG.Date = DateTime.Now.ToString();
            tB_LOG.Action = "Suppression d'une version : '" + tB_VERSION.Nom + "'";
            tB_LOG.Texte = "Nom de la version : '" + tB_VERSION.Nom + "'/Separation/Description : '" + tB_VERSION.Description + "'";
            db.TB_LOG.Add(tB_LOG);

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // Récupération derniere version pour le menu
        [ChildActionOnly]
        [ValidateInput(false)]
        [AllowAnonymous]
        public ActionResult GetLastVersion()
        {
            int flag = 0;
            var VersionLinq = from version1 in db.TB_VERSION
                              where version1.prod == "1"
                              select version1;

            //foreach (var item in VersionLinq)
            //{
            //    flag = 1;
            //    ViewBag.Num_Version = item.Nom;
            //}

            if (flag == 0)
            {
                ViewBag.Num_Version = "0.0";
            }

            return PartialView("_LastVersion");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ExpeditionHelper_SOL/Views/Version/Create.cshtml
@model ExpeditionHelper_SOL.Models.TB_VERSION

<div class="container body-content" style="background-color:white;border-radius:5px;">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <br /><br />
              <h4>@ExpeditionHelper_SOL.Resources.Views.Version.Create.Title</h4>
        <hr />
        <a href="@Url.Action("Index" , "Version")" class="btn btn-primary"><i class="fa fa-arrow-circle-left"></i> @ExpeditionHelper_SOL.Resources.Views.Version.Create.BtnRetour </a>
        <br /><br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">@ExpeditionHelper_SOL.Resources.Views.Version.Create.Version</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">@ExpeditionHelper_SOL.Resources.Views.Version.Create.Auteur</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Auteur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Auteur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">@ExpeditionHelper_SOL.Resources.Views.Version.Create.Description</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Date</label>
            <div class="col-md-10">
                <input type="date" class="form-control" name="Date_Prod" value="" />
                @Html.ValidationMessageFor(model => model.Date_Prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">@ExpeditionHelper_SOL.Resources.Views.Version.Create.Version_Prod</label>
            <div class="col-md-10">
                <label> <input type="radio" name="prod" value="1" /> @ExpeditionHelper_SOL.Resources.Views.Version.Create.Oui </label>
                <label> <input type="radio" name="prod" value="0" /> @ExpeditionHelper_SOL.Resources.Views.Version.Create.Non </label>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@ExpeditionHelper_SOL.Resources.Views.Version.Create.BtnValider" class="btn btn-success" />
            </div>
        </div>
    </div>
    }

</div>

ExpeditionHelper_SOL/Views/Version/Delete.cshtml
@model ExpeditionHelper_SOL.Models.TB_VERSION

<div class="container body-content" style="background-color:white;border-radius:5px;">
    <br /><br />
          <h3>@ExpeditionHelper_SOL.Resources.Views.Version.Delete.Titre</h3>
    <div>
        <hr />
        <a href="@Url.Action("Index" , "Version")" class="btn btn-primary"><i class="fa fa-arrow-circle-left"></i> @ExpeditionHelper_SOL.Resources.Views.Version.Delete.BtnRetour </a>
        <br /><br />
        <dl class="dl-horizontal">
            <dt>
                @ExpeditionHelper_SOL.Resources.Views.Version.Delete.Version
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nom)
            </dd>

            <dt>
                @ExpeditionHelper_SOL.Resources.Views.Version.Delete.Auteur
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Auteur)
            </dd>

            <dt>
                @ExpeditionHelper_SOL.Resources.Views.Version.Delete.Description
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @ExpeditionHelper_SOL.Resources.Views.Version.Delete.Date
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Date_Prod)
            </dd>

            <dt>
                @ExpeditionHelper_SOL.Resources.Views.Version.Delete.Prod
            </dt>

            <dd>
                @foreach (var item in ViewBag.VersionLinq)
                {
                    if (item.prod == "1")
                    {
                        <label>@ExpeditionHelper_SOL.Resources.Views.Version.Delete.Oui</label>
                    }
                    if (item.prod == "0")
                    {
                        <label>@ExpeditionHelper_SOL.Resources.Views.Version.Delete.Non</label>
                    }
                }
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="@ExpeditionHelper_SOL.Resources.Views.Version.Delete.BtnSupp" class="btn btn-danger" />
                </div>
            </div>
        }
    </div>
</div>

ExpeditionHelper_SOL/Views/Version/Edit.cshtml
@model ExpeditionHelper_SOL.Models.TB_VERSION


<div class="container body-content" style="background-color:white;border-radius:5px;">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <br /><br />
        <h4>@ExpeditionHelper_SOL.Resources.Views.Version.Edit.Titre @Html.DisplayFor(model => model.Nom)</h4>
        <hr />
        <a href="@Url.Action("Index" , "Version")" class="btn btn-primary"><i class="fa fa-arrow-circle-left"></i> @ExpeditionHelper_SOL.Resources.Views.Version.Edit.BtnRetour </a>
        <br /><br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <label class="control-label col-md-2">@ExpeditionHelper_SOL.Resources.Views.Version.Edit.Version</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">@ExpeditionHelper_SOL.Resources.Views.Version.Edit.Auteur</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Auteur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Auteur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">@ExpeditionHelper_SOL.Resources.Views.Version.Edit.Description</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">@ExpeditionHelper_SOL.Resources.Views.Version.Edit.Date</label>
            <div class="col-md-10">
                @foreach (var item in ViewBag.VersionLinq)
                {
                    <input type="date" class="form-control" name="Date_Prod" value="@item.Date_Prod" />
                }
                @Html.ValidationMessageFor(model => model.Date_Prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">@ExpeditionHelper_SOL.Resources.Views.Version.Edit.Prod</label>
            <div class="col-md-10">
                @foreach (var item in ViewBag.VersionLinq)
                {
                    if (item.prod == "1")
                    {
                        <label> <input type="radio" name="prod" value="1" checked /> @ExpeditionHelper_SOL.Resources.Views.Version.Edit.Oui </label>
                        <label> <input type="radio" name="prod" value="0" /> @ExpeditionHelper_SOL.Resources.Views.Version.Edit.Non </label>
                    }
                    if (item.prod == "0")
                    {
                        <label> <input type="radio" name="prod" value="1" /> @ExpeditionHelper_SOL.Resources.Views.Version.Edit.Oui </label>
                        <label> <input type="radio" name="prod" value="0" checked /> @ExpeditionHelper_SOL.Resources.Views.Version.Edit.Non </label>
                    }
                }
                @Html.ValidationMessageFor(model => model.prod, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@ExpeditionHelper_SOL.Resources.Views.Version.Edit.BtnValider" class="btn btn-success" />
            </div>
        </div>
    </div>
    }
    
</div>

ExpeditionHelper_SOL/Views/Version/Index.cshtml
@model PagedList.IPagedList<ExpeditionHelper_SOL.Models.TB_VERSION>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index version";
}

<div class="container body-content" style="background-color:white;border-radius:5px;">
    <br /><br />
    <h2>Version</h2>

    @if ((Session["Type_Connexion"] == "Acces_Digitalisation") || (Session["Type_Connexion"] == "Acces_Admin")) {
        <a href="@Url.Action("Create", "Version")" class="btn btn-primary"> <span class="fa fa-plus" aria-hidden="true"></span> @ExpeditionHelper_SOL.Resources.Views.Version.Index.BtnAdd </a> <br /><br /><br />
    }

    <div class="row">
        <div class="col-lg-3">
            @using (Html.BeginForm("Index", "Version", FormMethod.Get, new { @class = "form-inline" }))
            {
                <p>
                    @ExpeditionHelper_SOL.Resources.Views.Shared._Layout.SearchByName <br /> @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control text-box" })
                    <button type="submit" class="btn btn-default">
                        <i class="fa fa-search" aria-hidden="true"></i>
                    </button>
                </p>
            }
        </div>
    </div>

    <table class="table table-bordered">
        <tr>
            <th>
                @ExpeditionHelper_SOL.Resources.Views.Version.Index.Version
            </th>
            <th>
                @ExpeditionHelper_SOL.Resources.Views.Version.Index.Auteur
            </th>
            <th>
                @ExpeditionHelper_SOL.Resources.Views.Version.Index.Descriptif
            </th>
            <th>
                @ExpeditionHelper_SOL.Resources.Views.Version.Index.Date_Mise_En_Prod
            </th>
            <th>
                @ExpeditionHelper_SOL.Resources.Views.Version.Index.En_Prod
            </th>
            @if ((Session["Type_Connexion"] == "Acces_Digitalisation") || (Session["Type_Connexion"] == "Acces_Admin"))
            {
                <th>
                    @ExpeditionHelper_SOL.Resources.Views.Version.Index.Action
                </th>
            }
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Auteur)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date_Prod)
                </td>
                <td>
                    @if (item.prod == "1")
                    {
                        <label> @ExpeditionHelper_SOL.Resources.Views.Version.Index.Oui </label>
                    }
                    @if (item.prod == "0")
                    {
                        <label> @ExpeditionHelper_SOL.Resources.Views.Version.Index.Non </label>
                    }
                </td>
                @if ((Session["Type_Connexion"] == "Acces_Digitalisation") || (Session["Type_Connexion"] == "Acces_Admin"))
                {
                    <td>
                        <a href="@Url.Action("Edit" , "Version" , new { id = item.Id })" class="btn btn-primary"> <i class="fa fa-pencil"></i> </a>
                        <a href="@Url.Action("Delete" , "Version" , new { id = item.Id })" class="btn btn-danger"> <i class="fa fa-trash"></i> </a>
                    </td>
                }
            </tr>
        }

    </table>

    @ExpeditionHelper_SOL.Resources.Views.Shared._Layout.Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</div>